project: 
  type: website
  #Activate this code if we have scripts in the code folder and we don't want them reguarly rendered.
  # output-dir: docs 
  # render:
  #   - "*.qmd"Z

website: 
  page-navigation: true
  title: "CRP_PC_TowedArray" 
  site-url: "https://scaling-robot-wgqml1r.pages.github.io/" 
  repo-url: "https://github.com/noaa-pifsc/CRP_PC_TowedArray"
  repo-actions: [edit, source, issue]
  favicon: images/favicon.ico
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    background: "#BDCCD2"
    logo: images/FKW_OnlyWRing.png
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://www.fisheries.noaa.gov/pacific-islands/population-assessments/passive-acoustics-pacific-islands
        text: "NOAA Fisheries PIFSC - Passive Acoustic Monitoring"
        target: _blank
      - icon: github
        href: https://github.com/SAEL-SWFSC/PAM_template_ResearchCompendium
        text: "NMFS PAM SI Research Compendium Template"
        target: _blank

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: content/Metadata.qmd
        text: "Metadata"
      - href: content/Analysis_Methods.qmd
        text: "Analysis_Methods"
      - href: content/BANTER_Predict.qmd
        text: "BANTER Predict"
      - href: content/Data_ReadMe.qmd
        text: "Data ReadMe"
      - href: content/folderStructure.qmd
        text: "GitHub Folder Structure & Content"

        
format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
