---
title: "Home"
subtitle: "Localization of False Killer Whales"
page-layout: full
---

## Reseach Goals

Cetacean Research Program's analysis efforts to localize false killer whale subgroups from towed hydrophone arrays.

To understand movement of false killer whales (FKW) relative to a research vessel by linking visual sightings with towed array acoustic localizations. Evaluating animal movement is important for FKW abundance estimates as movement violates a distance sampling assumption.

## Dataset

Acoustic Data - Towed hydrophone array using largest spacing possible (Ranging \~25 to 45 m)

-   Visually confirmed detections of false killer whales (*Pseudorca crassidens*) collected during survey efforts throughout the Hawaiian Islands in 2017 (DCLDE 2022 dataset; Yano et al. 2018)

-   Acoustic only encounters were confirmed with the [*banter*](https://github.com/EricArcher/banter){target="_blank"} classifier published in McCullough et al. 2021. [BANTER_Predict](https://github.com/jlkeating/BANTER_Predict){target="_blank"}

-   Encounters ranged from at few minutes to 2 hours while the ship traveled at 10 knots without turning

-   Sensitivity analysis manuscript (Barkley et al. in prep) defines what "usable" encounters (events) are and how we validated acoustic encounters of false killer whales that had no visual indentification. 

## Analysis Steps

-   Time-Difference-Of-Arrivals (TDOAs) for all FKW signals were automatically extracted into tracks and then aggregated into continuous TRACES based on consistent TDOA trajectories using a multi-target Bayesian framework. (Custom MATLAB Script, Gruden et al. 2021 & 2023) [TDOA_tracking_master](https://github.com/PinaGruden/TDOA_tracking_master){target="_blank"}

-   Localization of the TRACES was done using modified localization Matlab code from Barkley et al.(2021) by Pina Gruden [Localization_Towed_Array](https://github.com/PinaGruden/Localization_Towed_Array){target="_blank"}.

-   Either both (echolocation clicks & whistles), echolocation clicks only, or whistles only were used during analysis to generate complete TRACES

-   Perpendicular distance to the trackline was computed at the beam for acoustically-detected TRACES, creating an acoustic detection function.

## Project Time

[Toolbox Timeline](https://docs.google.com/spreadsheets/d/160qWi3AINYFSISzhsMcmii3Qch1bzGty5HJ6ZO4q4L4/edit?usp=sharing){target="_blank"}\

## References

*Barkley, Yvonne M., Eva-Marie Nosal, and Erin M. Oleson. 2021. “Model-Based Localization of Deep-Diving Cetaceans Using Towed Line Array Acoustic Data.” The Journal of the Acoustical Society of America 150 (2): 1120.*

*Bradford AL, Becker E, Oleson EM, Forney K, Moore J, Barlow J. 2020. “Abundance estimates of false killer whales in Hawaiian waters and the broader central pacific,” NOAA Tech Memo NMFS-PIFSC-104*

*Gruden, Pina, Y. M. Barkley, and J. L. K. McCullough. 2023. “Vocal Behavior of False Killer Whale (Pseudorca Crassidens) Acoustic Subgroups.” Frontiers in Marine Science 10:1147670. https://doi.org/10.3389/fmars.2023.1147670.*

*Gruden, P., Nosal, E.-M., and Oleson, E. (2021). Tracking time differences of arrivals of multiple sound sources in the presence of clutter and missed detections. J. Acoust. Soc. America 150 (5), 3399–3416. doi: 10.1121/10.0006780*

*McCullough, Jennifer L. K., Anne E. Simonis, Taiki Sakai, and Erin M. Oleson. 2021. “Acoustic Classification of False Killer Whales in the Hawaiian Islands Based on Comprehensive Vocal Repertoire.” JASA Express Letters 1 (7). https://doi.org/10.1121/10.0005512.*

*Yano KM, Oleson EM, Keating JL, Balance LT, Hill MC, Bradford AL, Allen AN, Joyce TW, Moore JE, Henry A. 2018. “Cetacean and Seabird Data Collected During the Hawaiian Islands Cetacean and Ecosystem Assessment Survey (HICEAS), July-December 2017.” NOAA Tech Memo NMFS-PIFSC-72*
